### ISSUE TITLE
Cannot play remote video

### ISSUE THREAD

**Issue by Statali** [bradmartin/nativescript-videoplayer#18]
Hi @bradmartin 
I'm trying to play remote video by changing the source content with the link as 
`src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"`. I've an error CAN'T PLAY VIDEO on android 4.4.2.

I'll like to know if it's possible to play some remote video via rstp, rtmp protocol with links (rtsp://52.58.174.38/vod/sample.mp4, rtmp://52.58.174.38/vod/mp4:sample.mp4).  Ohers remote file I'll like to play is MPEG DASH file (http://52.58.174.38/vod/mp4:sample.mp4/manifest.mpd). Brief I want play VOD streaming in an android application build with Nativescript.

**Comment by bradmartin** [comment]
Hi @Statali - thanks for checking out the plugin. I believe that error is when Android blocks or can't read the video file. If you attempt to play a Youtube url .mp4 you'll see that error all the time because Google has a YouTube SDK that you are supposed to use for YouTube vides - just FYI.

As for rtsp/rtmp protocol I don't have any experience with so I can't say. However, [here is the official Android](https://developer.android.com/guide/appendix/media-formats.html) doc on what is supported for video which *RTSP* is listed. So I think you'll be okay with RTSP as long as there aren't issues with the video you're attempting to play.

Do let me know more info about the URL you are attempting to use when receiving the error `CAN'T PLAY VIDEO`

**Comment by AdamDiment** [comment]
Hi Brad, I'm attempting to play a remote video from vimeo with the url https://vimeo.com/134605960. The videoplayer loads fine but in the "disabled" state. There are no errors in the terminal. Looking at your answer above re youtube, would you agree it suggests a similar problem in that I must use the vimeo sdk to access the video? And the route to fixing this would be for me to look at writing my own plugins for the vimeo android / ios sdks?

**Comment by bradmartin** [comment]
If this happens on android, does it show a dialog with: can't play this
video (or something like that)? If so and if vimeo has an sdk that's
probably the best way to go about it.

**Comment by AdamDiment** [comment]
Hi yes that's exactly what happens on Android. Vimeo has a supported SDK for iOS and there are open source ones for Android.  Ok, I have a decision to make then whether I invest to make the plugin on effort vs reward! Thanks for the quick reply.

**Comment by bradmartin** [comment]
Yea I've never dug real deep on why android does that with certain videos.
You could use a webview and size it to your layout so it fits into your app
in a nice way if you wanted to skip the sdk route

**Comment by bradmartin** [comment]
Closing - remote videos will work on Android. Android is just a little specific about playback of all video files. Not an issue with this plugin though :+1:
