### ISSUE TITLE
Can't play this video (android device) using url to mp4 as video source

### ISSUE THREAD

**Issue by scemis** [bradmartin/nativescript-videoplayer#31]

**Comment by bradmartin** [comment]
Do you have any info about this?

**Comment by scemis** [comment]
what kind of info do you need?

**Comment by bradmartin** [comment]
A lot :) but I'm thinking you have a bad video mp4. Or you're trying to
play YouTube videos. Did you receive a dialog popup saying the video
couldn't play? If so it's not the plugin but the video. The encoding has to
be perfect or android doesn't like it. It's a PITA. If it's a YouTube link
android blocks it also because you're supposed to use the YouTube sdks
provided by Google.

If none of these send the plugin version, the URL, NativeScript versions
and I'll try to reproduce.

**Comment by scemis** [comment]
Actually, I try to find way how to write app with ability to play video
from url (mp4).
Exactly when I run app on real device I got that message.

Do you have some sample code using url as source for your plugin?

Thanks a lot in advance.

**Comment by bradmartin** [comment]
In the demo there is a URL on the xml page. Might even be on the README.

**Comment by bnussey** [comment]
I've had this issue myself with URLs on Android but have done it successfully.. It could possibly be the transcoding of the file, or are you using angular2? Sometimes the URL is not ready for the videoplayer if you're doing it in a *ngFor.. 

If that's not the case, I'd recommend just trying it with another URL hardcoded. Big buck bunny is always a good test.

**Comment by scemis** [comment]
Thanks for your reply.

I use TypeScript / Angular 2. (Hello Word template from nativescript
website) I will try to use just TypeScript.

Thanks a lot!

**Comment by bnussey** [comment]
Try and hardcode the URL instead and see if that works.

Also I added a timeout in the latest version of the plugin to the Android code base so make sure you're using that.

**Comment by scemis** [comment]
Issue fixed, I just added manifest (AndroidManifest.xml) to Android folder with Internet permission for the user (<uses-permission android: name = "android.permission.INTERNET" />)

Thanks a lot for your help in the process to solve that issue.
