### ISSUE TITLE
calling components functions using Angular Native.

### ISSUE THREAD

**Issue by adnanakbar** [bradmartin/nativescript-videoplayer#56]
I am using Angular Native and its working fine to display the video. Now I want to call the api functions e.g pause() from a another button tap. How do I do this? I am using type script and I only have access to VideoPlayer in html file. I tried with a local variabel <VideoPlayer #vPlayer, and then call vPlayer.pause() from a button (tap) event but it doesn't work. Also I was wondering if I can have access to instance of this in my compnent (.ts file), I can then call the events. Please help how should I get this working. Thanks.

**Comment by bradmartin** [comment]
Once you have an instance of the component you can use the methods exposed certainly. Can you share the code? Then we can figure out where your problem is.

**Comment by adnanakbar** [comment]
I got it working like the code below with passing the local variable of the video instance to the component. **However I can't change the source of the video, you can see in the component code that I tried different things. As per your code in your demo, if we just change the source it should work, but it not. Please help!**

//Html COde
<VideoPlayer #vPlayer
                            src="https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
                            autoplay="true" 
                            height="300" controls="true" >
                            </VideoPlayer>

<Button text="Video" (tap)="videoTap( vPlayer)"></Button>

//Component Code:

  videoTap(exercise: Exercise, vPlayer: Video) {
    //vPlayer.pause();
    vPlayer.src = "http://www.html5videoplayer.net/videos/toystory.mp4";
    //vPlayer.play();
    //vPlayer.pause();

  }

**Comment by adnanakbar** [comment]
Thanks for the help, actually I found another issue. I will raise separate issue for that. closing this.

**Comment by b4rtt** [comment]
This way how to destroy video doesn't working for me.
App crashes and this is in terminal:

`file:///app/pages/article/article.page.js:64:16: JS ERROR TypeError: undefined is not an object (evaluating 'vPlayer.destroy')
Apr  9 11:50:58 Roman-MacBook-Air SpringBoard[36897]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus
Apr  9 11:50:58 Roman-MacBook-Air com.apple.CoreSimulator.SimDevice.AB4B81E5-D9EF-40EB-B3D9-CDACC149964A.launchd_sim[36880] (UIKitApplication:org.romansimr.HelloWorld[0x18bc][36902][36968]): Service exited due to Segmentation fault: 11
Apr  9 11:50:58 Roman-MacBook-Air backboardd[36898]: [Common] Unable to get short BSD proc info for 36968: No such process`
