### ISSUE TITLE
Android demo autoplay="false" doesn't display anything

### ISSUE THREAD

**Issue by bachras** [bradmartin/nativescript-videoplayer#67]
Hi,

Thanks for great plugin. I just tried demo app and noticed that if autoplay="false" video and controls are not displayed. If I click on videoplayer area controls appears, then i click "play" and video appears and starts playing normally. It happens only on Android as ios works without any issue. Is this normal behaviour or there is any workaround? Any help would be appreciated. Thanks

**Comment by bradmartin** [comment]
That sounds exactly like Android video player works. Just like YouTube and
other video apps so think you're good to go :)

**Comment by bachras** [comment]
@bradmartin thanks for prompt reply, but youtube videos has a poster (preview image) which engages users. Is any way to do something like that here, as of now user sees only black screen. How they should now that video is there? Thnaks

**Comment by bradmartin** [comment]
One way is to use a Gridlayout and put an image on the same row/col as the
video player. Add a tap event to the image that removes it on tap and
programmatically start the video.

If you get stuck on it let me know. As for adding a preview from the video
my guess is YouTube uses an enhanced version of the media player, likely
ExoPlayer. Which @Nathanaela just released as a fork of this plugin. Search
for Nativescript-ExoPlayer and see if it loads up a still image of the
video. If so my guess is that's what YouTube uses since it's a Google
extension lib.

**Comment by bachras** [comment]
I have tried Nativescript-ExoPlayer, but I couldn't see any difference from Nativescript-videoplayer. Thank you for suggestion with the image, I will try to implement that. I have one question regarding controls, should I create new issue? Thanks

**Comment by bradmartin** [comment]
That they aren't visible until tapping? Yea - I forget the specifics of the controls behavior but it's possible we can add a property that enables them to show initially. So let's track it with a new issue. 

I played around with the YouTube app on android just now and from the behavior of it I think they're using images on the videoplayer control to hint the video. Because the image (on the videos I played) is not the first frame in the actual video. So it appears they use an image like a place holder which is what I suggested earlier. So keep me posted on how that works out for you 👍

**Comment by NathanaelA** [comment]
@bachras - I'm 99% sure the exoplayer shows the first frame with autoplay=off.

**Comment by bachras** [comment]
@bradmartin and @NathanaelA  you are both right, it does display first frame, I just got confused as the first frame of sample video is the black screen :) My mistake. I just noticed another problem with Android, it is not displaying most of my videos. @bradmartin mentioned in other issues that Android is very picky with videos. Any chance you know what could be wrong with my videos as I convert all of them to mp4 without changing anything. Thanks

**Comment by bnussey** [comment]
Hi @bachras I'd recommend giving exoplayer a go if its not playing videos.

**Comment by bachras** [comment]
I have tried on both: 
Video player shows: 
`W/System.err(12430): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err(12430): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
W/System.err(12430): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
W/System.err(12430): 	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
W/System.err(12430): 	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
W/System.err(12430): 	at com.tns.Runtime.callJSMethod(Runtime.java:1018)`

exoplayer shows:
`JS: PlayerError com.google.android.exoplayer2.ExoPlaybackException`

I tried to find out what is wrong with some videos and narrowed down that rotation from portrait to landscape mode using ffmpeg library ruins the video. Does anybody have any ideas ? Thanks

**Comment by klever34** [comment]
exoplayer shows PlayerError com.google.android.exoplayer2.ExoPlaybackException
any help on this?

**Comment by NathanaelA** [comment]
@klever34 - Exoplayer is not part of this repo; I believe you want to post this issue to http://github.com/nathanaela/nativescript-exoplayer  and you need to post more information about what you are doing to cause it to fail.
